name: flutter_soloud
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  logging: ^1.2.0
  meta: ^1.0.0
  ffi: ^2.1.2
  http: ^1.2.1

  # js_interop: ^3.3.0
  # js_interop_unsafe: ^3.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  flutter_test: 
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      web:
        pluginClass: FlutterSoloudWeb
        fileName: flutter_soloud_web.dart

  assets:
    - web/worker.dart.js
    - web/libflutter_soloud_plugin.js
    - web/libflutter_soloud_plugin.wasm
  